### ISSUE TITLE
A question for the plot utilities

### ISSUE THREAD

**Issue by renaomin** [SFU-MARS/optimized_dp#15]
Hi, thanks for the open-source, a new python toolbox optimized_dp. 

The MATLAB toolbox helperOC provides a strong visualization interface and many optional parameters for customized needs. For example, the "visSetIm()" command allows visualizing 3D or 2D sets. But I couldn't find such visualization scripts in the python toolbox, so I wonder if this is the latest version? Or is the python version not intended to provide similar visualization capabilities?

Thank you!

**Comment by buinm** [comment]
Hi ,

What are you trying to do that is missing in the toolbox specifically? If you want to visualize the level set of a 3D array or higher we have this function here https://github.com/SFU-MARS/optimized_dp/blob/master/Plots/plotting_utilities.py with the plot_option defined in https://github.com/SFU-MARS/optimized_dp/blob/master/plot_options.py.

But we don't have 2D set visualization yet, but it should be easy to do with matplotlib contour library.

Let me know if that's what you're looking for.

**Comment by renaomin** [comment]
> Hi ,
> 
> What are you trying to do that is missing in the toolbox specifically? If you want to visualize the level set of a 3D array or higher we have this function here https://github.com/SFU-MARS/optimized_dp/blob/master/Plots/plotting_utilities.py with the plot_option defined in https://github.com/SFU-MARS/optimized_dp/blob/master/plot_options.py.
> 
> But we don't have 2D set visualization yet, but it should be easy to do with matplotlib contour library.
> 
> Let me know if that's what you're looking for.

Thank you so much for the reply!

Yeah, I know the code you pointed out for me. I just think the plot function may not be so complete (e.g., grids, tubes, sets..). But like you said, it's easy to do with matplotlib. 

Thank you again for your kindness! It did help!

**Comment by renaomin** [comment]
@buinm Hi, Buinm,
Can the optimized_DP provide the function to retrieve a trajectory from some user-defined initial states? I know it is provided in the Helper-OC toolbox, but I wonder if optimized_DP would have this function?

**Comment by buinm** [comment]
yes, I will update with this function soon. Stay tuned

**Comment by matthew-william-lock** [comment]
> Hi ,
> 
> What are you trying to do that is missing in the toolbox specifically? If you want to visualize the level set of a 3D array or higher we have this function here https://github.com/SFU-MARS/optimized_dp/blob/master/Plots/plotting_utilities.py with the plot_option defined in https://github.com/SFU-MARS/optimized_dp/blob/master/plot_options.py.
> 
> But we don't have 2D set visualization yet, but it should be easy to do with matplotlib contour library.
> 
> Let me know if that's what you're looking for.

Is there any update on 2d viz? 😄

**Comment by buinm** [comment]
Added 2D set visualizations functionality. Please see examples/examples.py.

**Comment by renaomin** [comment]
> Added 2D set visualizations functionality. Please see examples/examples.py.

Hi. Thank you so much for maintaining the toolbox and contributing to the community. I would like to ask, does the current toolbox support to synthesize and retrieve control variables? Other toolbox like helpOC supports this functionality.
