### ISSUE TITLE
Accessing spatial derivatives and/or optimal controls in HJ Reachability

### ISSUE THREAD

**Issue by rallen10** [SFU-MARS/optimized_dp#18]
I'd like to be able to retrieve/utilize the spatial derivatives (or more specifically the optimal controls) at each state in the discretized state space. These values are computed during the PDE solution process [here](https://github.com/SFU-MARS/optimized_dp/blob/4724edaa408832fe2b125fc68ded9d60fdf3a458/odp/computeGraphs/graph_4D.py#L100), but they don't appear to be stored anywhere. 

I don't have experience working with heteroCL so the computation process is nebulous to me. Can someone provide an example of computing the spatial derivatives given a grid `g` and solved value function `V` on the grid?

**Comment by mochen72** [comment]
@buinm : could you please take a look? It seems like this shouldn't be too difficult to do.

**Comment by buinm** [comment]
Yeah the spatial derivatives were not accessible to users or stored at all. 
I just pushed some codes that allow calling the spatial derivatives function in python. Please pull the project again to get the newest updates. I also updated examples/examples.py to demonstrate how to compute the optimal control at any state. Let me know if that helps and if you have any other questions/suggestions.

**Comment by rallen10** [comment]
@buinm Thanks! I will try to use these changes today and I will update this comment with questions/suggestions

**Comment by rallen10** [comment]
Thanks! These updates seem to do the trick and the new [example.py](https://github.com/SFU-MARS/optimized_dp/blob/f13876dfc7ae9b42a3261aba239cfb255266cd1b/examples/examples.py) is very helpful!
